[package]
name = "openweather"
version = "0.1.0"
authors = ["kilroy <tsbach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version="0.2.22",  features = ["macros", "tcp", "dns", "io-util"]}
reqwest = "0.10.7"
serde = {version="1.0.114", features = ["derive"]}
serde_json= "1.0"
dotenv = "0.15.0"


